Add tts and speecht5 components helm chart
opea-project/GenAIInfra pull request #174
Opened 2024-07-16 07:55 UTC by yongfengdu

## Description

Add tts and speecht5 components helm chart

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds new functionality)

2024-07-16 08:03 UTC, lianhao approved these changes

2024-07-16 08:29 UTC, lianhao requested changes

2024-07-16 08:29 UTC, lianhao commented on helm-charts/common/speecht5/templates/tests/test-pod.yaml
> +          curl http://{{ include "speecht5.fullname" . }}:{{ .Values.service.port }}/v1/tts \
please add curl parameter `-sS --fail-with-body` to make sure curl will return error in case of HTTP status code >400

2024-07-16 08:29 UTC, lianhao commented on helm-charts/common/tts/templates/tests/test-pod.yaml
> +          curl http://{{ include "tts.fullname" . }}:{{ .Values.service.port }}/v1/audio/speech \
ditto

2024-07-16 08:42 UTC, lianhao approved these changes
LGTM

2024-07-17 01:50 UTC, leslieluyu approved these changes

2024-07-17 02:02 UTC, merged