Change tgi tag because gaudi driver is upgraded to 1.16.1
opea-project/GenAIInfra pull request #205
Opened 2024-07-22 07:53 UTC by daisy-ycguo

## Description

Change tgi tag because gaudi driver is upgraded to 1.16.1

## Issues

n/a

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

n/a

## Tests

CI tests

2024-07-22 08:33 UTC, lianhao requested changes

2024-07-22 08:33 UTC, lianhao commented on .github/workflows/chart-e2e.yaml
> +              --set autodependency.enabled=true \ #${EXTRAPARAM} \
I this this is syntax error for calling helm. You don't need to change this line

2024-07-22 10:01 UTC, daisy-ycguo commented
The CI test is verified here: https://github.com/opea-project/GenAIInfra/actions/runs/10037728498

2024-07-22 10:12 UTC, lianhao approved these changes

2024-07-23 01:55 UTC, KfreeZ approved these changes

2024-07-23 01:55 UTC, merged