Add kubernetes manifest for CodeGen
opea-project/GenAIInfra pull request #40
Opened 2024-05-24 07:46 UTC by yongfengdu

Deploy the codegen by kubectl apply.

## Description

Add manifest to deploy with kubectl.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds new functionality)

2024-05-25 07:46 UTC, jfding reviewed
suggest to remove unused code instead of commenting out

2024-05-27 02:28 UTC, daisy-ycguo requested changes

2024-05-27 02:28 UTC, daisy-ycguo commented on manifests/CodeGen/xeon/README.md
> +
We don't need prebuild these images. These images will be ready in our first release.

2024-05-27 02:30 UTC, daisy-ycguo approved these changes
LGTM

2024-05-27 02:48 UTC, lianhao approved these changes
LGTM

2024-05-27 02:55 UTC, merged