helm: Add llm-faqgen-tgi support
opea-project/GenAIInfra pull request #436
Opened 2024-09-18 05:32 UTC by lianhao

## Description

- Add llm-faqgen-tgi support
- Add variant_xxx-values.yaml to support variants of the same chart

## Issues

Related to issue #280.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-09-18 05:38 UTC, lianhao commented
we expect to see test failure of "E2E test with helm charts / variant_faqgen-value" due to bug opea-project/GenAIComps#700. Let's wait until PR opea-project/GenAIComps#701 get merged

2024-09-18 06:15 UTC, yongfengdu requested changes

2024-09-18 06:15 UTC, yongfengdu commented on helm-charts/common/llm-uservice/templates/tests/test-pod.yaml
> +          # Try with docsum endpoint
s/docsum/faqgen/

2024-09-18 06:24 UTC, lianhao commented on helm-charts/common/llm-uservice/templates/tests/test-pod.yaml
> +          # Try with docsum endpoint
done

2024-09-19 02:14 UTC, yongfengdu approved these changes

2024-09-24 01:36 UTC, zhlsunshine approved these changes
LGTM, need to integrate to GMC in later.

2024-09-24 03:12 UTC, merged