ui: support variants for multiple examples
opea-project/GenAIInfra pull request #464
Opened 2024-10-08 06:40 UTC by Ruoyu-y

## Description

 Use a single helm chart to support multiple variants of UI. Change the values in config map and deployment accordingly.

## Issues

`n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

`n/a`.

## Tests

Run CI testing

2024-10-11 03:10 UTC, lianhao requested changes

2024-10-11 03:10 UTC, lianhao commented on helm-charts/common/ui/templates/configmap.yaml
> +  {{- else }}
maybe we should have same check logic for chatqna conversational ui related config too? i.e. 'else if contains'

and use helm `fail` to fail other non-supported images?

2024-10-23 07:35 UTC, lianhao requested changes
@Ruoyu-y  Could you please create symbolic link files to the variant_values files to enable ci tests? Just like https://github.com/opea-project/GenAIInfra/blob/main/helm-charts/common/ui/ci-values.yaml

2024-10-24 02:11 UTC, Ruoyu-y commented
> @Ruoyu-y Could you please create symbolic link files to the variant_values files to enable ci tests? Just like https://github.com/opea-project/GenAIInfra/blob/main/helm-charts/common/ui/ci-values.yaml

Got it.

2024-10-30 02:15 UTC, lianhao approved these changes

2024-10-30 05:24 UTC, yongfengdu approved these changes

2024-10-30 05:24 UTC, merged