Implement the nowrapper version chatqna
opea-project/GenAIInfra pull request #474
Opened 2024-10-15 08:41 UTC by yongfengdu

Change the helm chart follow this commit
https://github.com/opea-project/GenAIExamples/commit/619d9410477408dcc51bc0058851e9e8f59185a2

CI changes first step

## Issues

#471 
Closed #466 

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-10-15 08:51 UTC, lianhao requested changes

2024-10-15 08:59 UTC, yongfengdu commented on helm-charts/chatqna/templates/deployment.yaml
> +              value: "80"
No, we're using the service port, which is hardcoded to 80 so far. The 2080 is the port of target pod, which shouldn't be used by others.
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: tgi

2024-10-15 09:00 UTC, lianhao approved these changes

2024-10-16 01:14 UTC, bjzhjing approved these changes

2024-10-16 01:16 UTC, daisy-ycguo approved these changes

2024-10-16 01:17 UTC, merged