[Feature] Added automated provisioning of CosmosDB and App Insights for OPEA applications  - Infosys
opea-project/GenAIInfra pull request #657
Opened 2024-12-24 10:40 UTC by kkrishTa

## Description

Infosys contribution to OPEA.
Added CosmosDB and App Insights to the terraform on Azure.

## Issues

NA

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

None

## Tests

Tested terraforms on Azure platform.

2024-12-26 11:49 UTC, mkbhanda reviewed
a few questions

2024-12-26 11:49 UTC, mkbhanda commented on cloud-service-provider/azure/aks/terraform/azure_main.tf
> +      path = "/*"
Does not /* cover everything? Is there some ordering effect here .. from most general to specific?

2024-12-26 11:49 UTC, mkbhanda commented on cloud-service-provider/azure/aks/terraform/azure_main.tf
> +  sku                 = "PerGB2018"
Do you really want to hard code sku or keep it a variable?

2025-01-07 09:25 UTC, poussa commented on cloud-service-provider/azure/aks/terraform/azure_main.tf
> +  sku                 = "PerGB2018"
[sku](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#sku-1) is not what one might think. `PerGB2018` is default, so we should leave it out for simplicity. If needed, we can add it later via variable.

2025-01-07 09:29 UTC, poussa commented
@kkrishTa thanks for the PR. I think this is good addition. Few questions below.

Can we make CosmosDB optional (opt-in)? User should have an option to include CosmosDB or leave it out.

Do we have any OPEA apps using CosmosDB?

2025-01-15 14:50 UTC, poussa requested changes
Can we make CosmosDB optional (opt-in)? User should have an option to include CosmosDB or leave it out.

Do we have any OPEA apps using CosmosDB?

2025-01-19 13:43 UTC, kkrishTa commented
> Can we make CosmosDB optional (opt-in)? User should have an option to include CosmosDB or leave it out.
> 
> Do we have any OPEA apps using CosmosDB?

Yes, We can make CosmosDB optional. Will update the code shortly.  Apologies for late reply.

2025-01-21 20:39 UTC, poussa commented on cloud-service-provider/azure/aks/terraform/variables.tf
> +variable "is_cosmosdb_required" {
Can you add default (false) so use is not asked every time?

2025-01-22 05:19 UTC, kkrishTa commented on cloud-service-provider/azure/aks/terraform/variables.tf
> +variable "is_cosmosdb_required" {
Added and added one more parameter in tfvars again defaulted to false.

2025-01-22 09:42 UTC, poussa approved these changes

2025-01-22 09:42 UTC, poussa commented
LGTM

2025-01-22 09:58 UTC, lianhao commented
Just FYI. v1.2rc branch is created minutes ago. If this PR is still targeted for v1.2, please set the milestone to v1.2, so Suyue can cherry-pick it to v1.2 rc branch later.

2025-01-22 11:15 UTC, kkrishTa commented
> Just FYI. v1.2rc branch is created minutes ago. If this PR is still targeted for v1.2, please set the milestone to v1.2, so Suyue can cherry-pick it to v1.2 rc branch later.

@poussa Will you be able to do this?

2025-01-22 22:03 UTC, mkbhanda approved these changes
LGTM

2025-01-22 22:09 UTC, merged