Add helm charts for deploy ChatQnA
opea-project/GenAIInfra pull request #68
Opened 2024-06-03 02:55 UTC by yongfengdu

Initial helm chart for ChatQnA

## Description

Helm chart for ChatQnA

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds new functionality)

2024-06-03 08:19 UTC, daisy-ycguo approved these changes
lgtm

2024-06-04 02:50 UTC, lianhao requested changes

2024-06-04 03:25 UTC, yongfengdu commented on helm-charts/chatqna/values.yaml
> +    port: 9000
removed unnecessary settings in values and gaudi-values.

2024-06-04 03:25 UTC, yongfengdu commented on helm-charts/chatqna/charts/retriever-usvc/templates/deployment.yaml
> +            - name: TGI_EMBEDDING_ENDPOINT
Good catch, changed.

2024-06-04 03:47 UTC, lianhao approved these changes

2024-06-04 05:46 UTC, merged